=== groud/esbtestmaster/ESBTestMaster/XSD/simulationScenario.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema
        xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="scenario">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="configuration">
          <xsd:complexType>
	     <xsd:sequence maxOccurs="unbounded">
            	<xsd:choice>
		      <xsd:element name="provider">
			<xsd:complexType>
			  <xsd:sequence>
			    <xsd:element type="xsd:string" name="name" minOccurs="1" maxOccurs="1"/>
			    <xsd:element type="xsd:string" name="address" minOccurs="1" maxOccurs="1"/>
			    <xsd:element type="xsd:string" name="monitoringAddress" minOccurs="1" maxOccurs="1"/>
			  </xsd:sequence>
			</xsd:complexType>
		      </xsd:element>
		      <xsd:element name="consumer">
			<xsd:complexType>
			  <xsd:sequence>
			    <xsd:element type="xsd:string" name="name" minOccurs="1" maxOccurs="1"/>
			    <xsd:element type="xsd:string" name="address" minOccurs="1" maxOccurs="1"/>
			    <xsd:element type="xsd:string" name="monitoringAddress" minOccurs="1" maxOccurs="1"/>
			  </xsd:sequence>
			</xsd:complexType>
		      </xsd:element>
            	</xsd:choice>
	    </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="run">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="burst" maxOccurs="unbounded" minOccurs="0">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element type="xsd:byte" name="rate"/>
                    <xsd:element type="xsd:int" name="requestPayloadSize"/>
                    <xsd:element type="xsd:long" name="processTime"/>
                    <xsd:element type="xsd:int" name="responsePayloadSize"/>
                  </xsd:sequence>
                  <xsd:attribute type="xsd:string" name="src" use="required"/>
                  <xsd:attribute type="xsd:string" name="dest" use="required"/>
                  <xsd:attribute type="xsd:byte" name="startdate" use="required"/>
                  <xsd:attribute type="xsd:byte" name="stopdate" use="required"/>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== groud/esbtestmaster/ESBTestMaster/sample2.xml
<?xml version="1.0"?>
<scenario
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="XSD/simulationScenario.xsd">
	<configuration>
		<consumer agentId="cons1">
			<address>http://lol.com:6666</address>
		</consumer>
	</configuration>
	<run>
		<burst src="cons1" dest="prov1" startdate="0" stopdate="10">
			<rate>30</rate>
			<requestPayloadSize>120</requestPayloadSize>
			<processTime>1000</processTime>
			<responsePayloadSize>100</responsePayloadSize>
		</burst>
		<burst src="cons1" dest="prov1" startdate="10" stopdate="20">
			<rate>30</rate>
			<requestPayloadSize>10</requestPayloadSize>
			<processTime>500</processTime>
			<responsePayloadSize>20</responsePayloadSize>
		</burst>
	</run>
</scenario>

=== groud/esbtestmaster/ESBTestMaster/sample4.xml
<?xml version="1.0"?>
<scenario
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="XSD/simulationScenario.xsd">
	<configuration>
		<consumer agentId="agent1"/>
		<producer agentId="agent2">
			<address>http://localhost:8090/ESBTestComposite2Service1/casaPort1</address>
		</producer>
               	<consumer agentId="agent3"/>
                <producer agentId="agent4">
                        <address>http://localhost:8090/ESBTestComposite4Service1/casaPort1</address>
                </producer>


	</configuration>
	<run>
		<burst src="agent1" dest="agent2" startdate="0" stopdate="5000">
			<rate>30</rate>
			<requestPayloadSize>10</requestPayloadSize>
			<processTime>500</processTime>
			<responsePayloadSize>20</responsePayloadSize>
		</burst>
                <burst src="agent3" dest="agent4" startdate="5000" stopdate="10000">
                        <rate>30</rate>
                        <requestPayloadSize>10</requestPayloadSize>
                        <processTime>500</processTime>
                        <responsePayloadSize>20</responsePayloadSize>
                </burst>
                <burst src="agent1" dest="agent4" startdate="10000" stopdate="15000">
                        <rate>30</rate>
                        <requestPayloadSize>10</requestPayloadSize>
                        <processTime>500</processTime>
                        <responsePayloadSize>20</responsePayloadSize>
                </burst>

	</run>
</scenario>
